# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-23 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(0, 'Info'), (1, 'Warning'), (2, 'Danger')], default=0)),
                ('log_from', models.CharField(max_length=128)),
                ('log_message', models.TextField()),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
