# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-22 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_auto_20180322_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='priority',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(default=0),
        ),
    ]
