# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-23 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0008_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='level',
            field=models.IntegerField(choices=[(0, 'Info'), (1, 'Warning'), (2, 'Danger')], default=0),
        ),
        migrations.AlterField(
            model_name='log',
            name='log_message',
            field=models.TextField(),
        ),
    ]
