# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-23 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0009_auto_20180323_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
