# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-24 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0010_log_datetime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.AlterField(
            model_name='room',
            name='svg_ids',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
