# Generated by Django 2.0 on 2018-05-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0011_auto_20180324_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='registered',
            field=models.IntegerField(default=0),
        ),
    ]
