# Generated by Django 2.0 on 2018-05-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0012_booking_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='seats',
            field=models.IntegerField(default=0),
        ),
    ]
