# Generated by Django 2.0 on 2019-05-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0014_booking_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
